FSHOOK_PATH_RD="/fshook"
FSHOOK_PATH_INSTALLATION="/system/bootmenu/2nd-system"
FSHOOK_PATH_RD_FILES="$FSHOOK_PATH_RD/files"
FSHOOK_PATH_RD_MOUNTS="$FSHOOK_PATH_RD/mounts"

FSHOOK_PATH_CONFIG_DEFAULTPATH="$BM_ROOTDIR/config/multiboot_defaultpath.conf"
FSHOOK_PATH_CONFIG_TEMPDEFAULTPATH="$FSHOOK_PATH_RD_MOUNTS/cache/recovery/multiboot_system.conf"

FSHOOK_PATH_MOUNT_SYSTEM="$FSHOOK_PATH_RD_MOUNTS/system"
FSHOOK_PATH_MOUNT_DATA="$FSHOOK_PATH_RD_MOUNTS/data"
FSHOOK_PATH_MOUNT_CACHE="$FSHOOK_PATH_RD_MOUNTS/cache"
FSHOOK_PATH_MOUNT_IMAGESRC="$FSHOOK_PATH_RD_MOUNTS/imageSrc"


MULTIBOOT_DEFAULT_PARTITION="/dev/block/mmcblk0p1"
MULTIBOOT_DEFAULT_PATH="/multiboot/default"